### ISSUE TITLE
Add Friends Fast.net shortcut to main menu

### ISSUE THREAD

**Issue by djmattyg007** [Kamikaze94/Enhanced-Fast.Net#1]
The original Fast.net standalone had a shortcut to opening Fast.net with the friends only filter applied. Would you be able to add this into your mod?

**Comment by Kamikaze94** [comment]
Yeah, I removed that on purpose, to reduce the amount of buttons on the main menu.
(Kind of like removing the filters from the node, and adding a button to access crimenet filters, to be able to display more lobbies without the need tio scroll...)
You can still filter by Friends only, and the persistent filters should keep the setting though...

**Comment by djmattyg007** [comment]
I liked having the extra menu item specifically because it meant I didn't have to use the filtering system to switch between friends-only and everyone.

Would it be possible to make this configurable?

**Comment by Kamikaze94** [comment]
Okay, readded the friends menu, and setup some simple options.
Those will need a restart to apply.
