### ISSUE TITLE
Trying to apply a difficulty filter for Mayhem-only causes a crash

### ISSUE THREAD

**Issue by killrhythm09** [Kamikaze94/Enhanced-Fast.Net#3]
[crash.txt](https://github.com/Kamikaze94/Enhanced-Fast.Net/files/547361/crash.txt)

This is with the most recent dev build.

**Comment by Kamikaze94** [comment]
Yeah, this is happening, if you click on apply filters.
Leaving filters with Esc and pressing G to manually refresh is working fine....
Trying hard to find the isse.
 ("_lookup(...) is for debugging only!" with empty callstack is not helpful, Overkill!!!!)

_Edit:_ Got that crash fixed, you can apply settings now. (Had an additional callback hooked into the crimenet filters to safe the settings, for persistent filter setting, that I forgot about..... stupid me.)
Anyways, looks like the settings currently don't get loaded, unless crimenet is opened once. Will have to look into that one closer.

**Comment by Kamikaze94** [comment]
Alright, filters are beeing loaded for FasteNet now, too.
Everything should be working again.  :)
